import type { Course } from '@/interfaces/course'

export const data: Array<Course> = [
  {
    id: 1,
    cover: '/images/courses/2.jpg',
    title: 'Paket Epic',
    rating: 5,
    ratingCount: 55,
    price: 125000,
    category: 'Beginner',
  },
  {
    id: 2,
    cover: '/images/courses/3.jpg',
    title: 'Paket Legend',
    rating: 5,
    ratingCount: 25,
    price: 150000,
    category: 'Intermediate',
  },
  {
    id: 3,
    cover: '/images/courses/4.jpg',
    title: 'Paket Mythic',
    rating: 5,
    ratingCount: 19,
    price: 200000,
    category: 'Beginner',
  },
  {
    id: 4,
    cover: '/images/courses/5.jpg',
    title: 'Paket Request',
    rating: 5,
    ratingCount: 6,
    price: 250000,
    category: 'Intermediate',
  },
  // {
  //   id: 5,
  //   cover: '/images/courses/stillness-inmotion-Jh6aQX-25Uo-unsplash.jpg',
  //   title: 'Modern React with MUI & Redux',
  //   rating: 4,
  //   ratingCount: 32,
  //   price: 35,
  //   category: 'Intermediate',
  // },
  // {
  //   id: 6,
  //   cover: '/images/courses/stillness-inmotion-YSCCnRGrD-4-unsplash.jpg',
  //   title: 'Ethical Hacking Bootcamp Zero to Mastery',
  //   rating: 5,
  //   ratingCount: 14,
  //   price: 35,
  //   category: 'Beginner',
  // },
  // {
  //   id: 7,
  //   cover: '/images/courses/grovemade-RvPDe41lYBA-unsplash.jpg',
  //   title: 'Adobe Lightroom For Beginners: Complete Photo Editing',
  //   rating: 4,
  //   ratingCount: 6,
  //   price: 25,
  //   category: 'Beginner',
  // },
]
